# The `service` block is the name of the service
service: serverless-auths

# Configuration variables
#custom:
  #secrets: ${file(env.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  iamRoleStatements:
    $ref: ./iamRoleStatements.json

# Lambda Functions Below Defined for Standup API
functions:
  getTeamMembers:
    handler: functions/liam-calls/getTeamMembers.handler
    events:
      - http:
          path: teammembers
          method: post
          cors: true
          #authorizer: aws_iam # Members are protected
  #getMember:
    #handler: functions/getMember.handler
    #events:
    #  - http:
     #     path: members/{id}
      #    method: get
          # request:
          #   parameters:
          #     paths:
          #       id: true
       #   cors: true
        #  authorizer: aws_iam # Members are protected

  getTeams:
   handler: functions/liam-calls/getChildTeams.handler
   events:
     - http:
         path: childteams
         method: post
         cors: true
  #        authorizer: aws_iam # 
  createTeam:
    handler: functions/liam-calls/createTeam.handler
    events:
      - http:
          path: teams
          method: post
          cors: true
          #authorizer: aws_iam # TODO: fixed cors
  createTeamMember:
    handler: functions/liam-calls/createTeamMember.handler
    events:
      - http:
          path: members
          method: post
          cors: true

resources:
  Resources:
    TeamsTbl:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ParentID
            AttributeType: S
          -
            AttributeName: ID
            AttributeType: S
        KeySchema:
          -
            AttributeName: ParentID
            KeyType: HASH
          -
            AttributeName: ID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'TeamsTbl'
    TeamMembersTbl:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: TeamID
            AttributeType: S
          -
            AttributeName: ID
            AttributeType: S
        KeySchema:
          -
            AttributeName: TeamID
            KeyType: HASH
          -
            AttributeName: ID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'TeamMembersTbl'
