# The `service` block is the name of the service
service: serverless-dev

# Configuration variables
#custom:
  #secrets: ${file(env.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  iamRoleStatements:
    $ref: ./iamRoleStatements.json

# Lambda Functions Below Defined for Standup API
functions:
  createTeam:
    handler: functions/createTeam.handler
    events:
      - http:
          path: createteam
          method: post
          cors: true
          #authorizer: aws_iam # Members are protected

  addChildTeam:
   handler: functions/addChildTeam.handler
   events:
     - http:
         path: addchildteam
         method: post
         cors: true
  #        authorizer: aws_iam # 
  teamInfo:
    handler: functions/teamInfo.handler
    events:
      - http:
          path: teaminfo
          method: post
          cors: true
          #authorizer: aws_iam # TODO: fixed cors
  createTeamMember:
    handler: functions/createTeamMember.handler
    events:
      - http:
          path: createteammember
          method: post
          cors: true    

resources:
  Resources:
    TeamList:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ID
            AttributeType: S
        KeySchema:
          -
            AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'TeamList'
        
    TeamMembersList:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: TeamID
            AttributeType: S
          -
            AttributeName: ID
            AttributeType: S
        KeySchema:
          -
            AttributeName: TeamID
            KeyType: HASH
          -
            AttributeName: ID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'TeamMembersList'

    TeamParentList:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ParentID
            AttributeType: S
          -
            AttributeName: ID
            AttributeType: S
        KeySchema:
          -
            AttributeName: ParentID
            KeyType: HASH
          -
            AttributeName: ID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'TeamParentList'
