# The `service` block is the name of the service
service: serverless-auths

# Configuration variables
#custom:
  #secrets: ${file(env.json)}

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    $ref: ./iamRoleStatements.json
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

# Lambda Functions Below Defined for Standup API
functions:
  getMembers:
    handler: functions/getMembers.handler
    events:
      - http:
          path: members
          method: get
          cors: true
          #authorizer: aws_iam # Members are protected
  #getMember:
    #handler: functions/getMember.handler
    #events:
    #  - http:
     #     path: members/{id}
      #    method: get
          # request:
          #   parameters:
          #     paths:
          #       id: true
       #   cors: true
        #  authorizer: aws_iam # Members are protected

  #getTeams:
  #  handler: functions/getTeams.handler
  #  events:
  #    - http:
  #        path: teams
  #        method: get
  #        cors: true
  #        authorizer: aws_iam # 
  createTeam:
    handler: functions/createTeam.handler
    events:
      - http:
          path: teams
          method: post
          cors: true
          #authorizer: aws_iam # TODO: fixed cors
resources:
  Resources:
    StandupsDynamoDbTableTeams:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ParentID
            AttributeType: S
          -
            AttributeName: ID
            AttributeType: S
        KeySchema:
          -
            AttributeName: ParentID
            KeyType: HASH
          -
            AttributeName: ID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'TeamsTbl'
    StandupsDynamoDbTableTeamMembers:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: TeamID
            AttributeType: S
          -
            AttributeName: ID
            AttributeType: S
        KeySchema:
          -
            AttributeName: TeamID
            KeyType: HASH
          -
            AttributeName: ID
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'TeamMembersTbl'
